baseURL = "https://quakewang.github.io/"
title = "AKA二夕"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "AKA二夕"
    badge = "orange"
    quote = "red"
    index_posts_num = 5
    # logo = "//blog.ertuil.top/avater.png"
    bio = """
    <p> This is my blog based on the boilerplate of Hugo. I want to share some notes about study here,and some interesting things about my life.</p>
    <br />
    <p>Also all html tags such as <a href="https://github.com/ertuil/erblog">link</a> are a good here.</p>
    """
    # copyright = "Copyright © 2008–2020, Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "mailto:username@mail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/username"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/username/"
    name = "instagram"
    weight = 1
