BaseUrl= "https://quakewang.github.io/"
LanguageCode= "en-US"
Title= "AKA二夕"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true

[author]
  name = "AKA二夕"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "This is my blog based on the boilerplate of Hugo. I want to share some  notes about study here,and some interesting things about my life."
  cover = "images/user.jpg"
  author = "AKA二夕"
  authorlocation = ""
  authorwebsite = "https://quakewang.github.io/"
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""

  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "QuakeWang"
  twitterName = ""

# set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")

  hideHUGOSupport = false
  mainSections = ["post"]
